name: Deploy QA → UAT

on:
  push:
    branches:
      - uat
  pull_request:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: UAT
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Auth UAT
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_UAT }}" > authfile.txt
          sfdx force:auth:sfdxurl:store -f authfile.txt -a UATPlayground

      - name: Deploy to UAT
        run: sfdx force:source:deploy -p force-app -u UATPlayground
